openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /enrollments:
    post:
      tags:
        - Enrollments
      summary: 수강신청
      operationId: enroll
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrollmentRequest"
        required: true
      responses:
        "409":
          description: 중복 신청
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "422":
          description: 학점/시간표/정원 규칙 위반
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "201":
          description: 수강신청 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "404":
          description: 학생 또는 강좌를 찾을 수 없음
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
  /enrollments/pessimistic:
    post:
      tags:
        - Enrollments
      summary: 수강신청 - 비관적 락 전략
      operationId: enrollWithPessimisticLock
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrollmentRequest"
        required: true
      responses:
        "422":
          description: 학점/시간표/정원 규칙 위반
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "201":
          description: 수강신청 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "409":
          description: 중복 신청 또는 동시성 충돌
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "404":
          description: 학생 또는 강좌를 찾을 수 없음
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
  /enrollments/optimistic:
    post:
      tags:
        - Enrollments
      summary: 수강신청 - 낙관적 락 전략
      operationId: enrollWithOptimisticLock
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrollmentRequest"
        required: true
      responses:
        "422":
          description: 학점/시간표/정원 규칙 위반
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "201":
          description: 수강신청 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "409":
          description: 중복 신청 또는 동시성 충돌
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "404":
          description: 학생 또는 강좌를 찾을 수 없음
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
  /enrollments/atomic:
    post:
      tags:
        - Enrollments
      summary: 수강신청 - 원자적 업데이트 전략
      operationId: enrollWithAtomicUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrollmentRequest"
        required: true
      responses:
        "422":
          description: 학점/시간표/정원 규칙 위반
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "201":
          description: 수강신청 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "409":
          description: 중복 신청 또는 동시성 충돌
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
        "404":
          description: 학생 또는 강좌를 찾을 수 없음
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponse"
  /students:
    get:
      tags:
        - Students
      summary: 학생 목록 조회
      operationId: getStudents
      parameters:
        - name: offset
          in: query
          description: 조회 시작 offset
          required: false
          schema:
            type: integer
            format: int32
          example: 0
        - name: limit
          in: query
          description: "조회 건수(limit, 최대 100)"
          required: false
          schema:
            type: integer
            format: int32
          example: 50
      responses:
        "200":
          description: 학생 목록 조회 성공
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudentResponse"
  /students/{studentId}/timetable:
    get:
      tags:
        - Timetable
      summary: 내 시간표 조회
      operationId: getTimetable
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: 시간표 조회 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TimetableResponse"
        "404":
          description: 학생을 찾을 수 없음
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TimetableResponse"
  /professors:
    get:
      tags:
        - Professors
      summary: 교수 목록 조회
      operationId: getProfessors
      parameters:
        - name: offset
          in: query
          description: 조회 시작 offset
          required: false
          schema:
            type: integer
            format: int32
          example: 0
        - name: limit
          in: query
          description: "조회 건수(limit, 최대 100)"
          required: false
          schema:
            type: integer
            format: int32
          example: 50
      responses:
        "200":
          description: 교수 목록 조회 성공
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProfessorResponse"
  /health:
    get:
      tags:
        - Health
      summary: 헬스체크
      description: 서버 정상 구동 여부를 반환합니다.
      operationId: health
      responses:
        "200":
          description: 서버 정상
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /courses:
    get:
      tags:
        - Courses
      summary: 강좌 목록 조회
      description: 전체 또는 학과별 강좌 목록을 조회합니다.
      operationId: getCourses
      parameters:
        - name: departmentId
          in: query
          description: 학과 ID 필터
          required: false
          schema:
            type: integer
            format: int64
          example: 3
        - name: offset
          in: query
          description: 조회 시작 offset
          required: false
          schema:
            type: integer
            format: int32
          example: 0
        - name: limit
          in: query
          description: "조회 건수(limit, 최대 100)"
          required: false
          schema:
            type: integer
            format: int32
          example: 50
      responses:
        "200":
          description: 강좌 목록 조회 성공
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CourseResponse"
  /enrollments/{enrollmentId}:
    delete:
      tags:
        - Enrollments
      summary: 수강취소
      operationId: cancel
      parameters:
        - name: enrollmentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: 수강취소 성공
        "404":
          description: 신청 정보를 찾을 수 없음
        "409":
          description: 이미 취소된 신청
components:
  schemas:
    EnrollmentRequest:
      required:
        - courseId
        - studentId
      type: object
      properties:
        studentId:
          type: integer
          description: 학생 ID
          format: int64
          example: 1
        courseId:
          type: integer
          description: 강좌 ID
          format: int64
          example: 101
      description: 수강신청 요청
    EnrollmentResponse:
      type: object
      properties:
        enrollmentId:
          type: integer
          description: 신청 ID
          format: int64
          example: 1001
        studentId:
          type: integer
          description: 학생 ID
          format: int64
          example: 1
        courseId:
          type: integer
          description: 강좌 ID
          format: int64
          example: 101
        status:
          type: string
          description: 신청 상태
          example: ACTIVE
      description: 수강신청 응답
    StudentResponse:
      type: object
      properties:
        id:
          type: integer
          description: 학생 ID
          format: int64
          example: 1
        studentNumber:
          type: string
          description: 학번
          example: "20260001"
        name:
          type: string
          description: 학생 이름
          example: 홍길동
        departmentId:
          type: integer
          description: 학과 ID
          format: int64
          example: 3
        departmentName:
          type: string
          description: 학과명
          example: 컴퓨터공학과
      description: 학생 목록 응답
    TimetableCourseResponse:
      type: object
      properties:
        courseId:
          type: integer
          description: 강좌 ID
          format: int64
          example: 101
        courseName:
          type: string
          description: 강좌명
          example: 자료구조
        credits:
          type: integer
          description: 학점
          format: int32
          example: 3
        schedule:
          type: string
          description: 강의 시간
          example: MON 09:00-10:30
        professorName:
          type: string
          description: 교수명
          example: 김교수
        departmentName:
          type: string
          description: 학과명
          example: 컴퓨터공학과
      description: 시간표 내 강좌 정보
    TimetableResponse:
      type: object
      properties:
        studentId:
          type: integer
          description: 학생 ID
          format: int64
          example: 1
        totalCredits:
          type: integer
          description: 현재 총 신청 학점
          format: int32
          example: 9
        courses:
          type: array
          items:
            $ref: "#/components/schemas/TimetableCourseResponse"
      description: 학생 시간표 응답
    ProfessorResponse:
      type: object
      properties:
        id:
          type: integer
          description: 교수 ID
          format: int64
          example: 10
        name:
          type: string
          description: 교수 이름
          example: 김교수
        departmentId:
          type: integer
          description: 학과 ID
          format: int64
          example: 3
        departmentName:
          type: string
          description: 학과명
          example: 컴퓨터공학과
      description: 교수 목록 응답
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: 애플리케이션 상태
          example: UP
      description: 헬스체크 응답
    CourseResponse:
      type: object
      properties:
        id:
          type: integer
          description: 강좌 ID
          format: int64
          example: 101
        courseCode:
          type: string
          description: 강좌 코드
          example: CSE301
        name:
          type: string
          description: 강좌명
          example: 자료구조
        credits:
          type: integer
          description: 학점
          format: int32
          example: 3
        capacity:
          type: integer
          description: 정원
          format: int32
          example: 30
        enrolled:
          type: integer
          description: 현재 신청 인원
          format: int32
          example: 25
        schedule:
          type: string
          description: 강의 시간
          example: MON 09:00-10:30
        departmentId:
          type: integer
          description: 학과 ID
          format: int64
          example: 3
        departmentName:
          type: string
          description: 학과명
          example: 컴퓨터공학과
        professorId:
          type: integer
          description: 교수 ID
          format: int64
          example: 12
        professorName:
          type: string
          description: 교수명
          example: 김교수
      description: 강좌 목록 응답
